SELECT TITLE,a.BOARD_ID,b.REPLY_ID,b.WRITER_ID,b.CONTENTS,DATE_FORMAT(b.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
from USED_GOODS_BOARD as a
INNER JOIN USED_GOODS_REPLY as b
on a.BOARD_ID = B.BOARD_ID
WHERE a.CREATED_DATE LIKE '2022-10%'
order by B.CREATED_DATE ASC, TITLE ASC;